name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            REPO="https://${{ secrets.GIT_TOKEN }}@github.com/KYKY62/backend_stunting_lkt.git"
            DIR="${{ secrets.APP_PATH }}"
            ./build.sh
