name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Show env
        run: |
          echo "Host: ${{ secrets.SSH_HOST }}"
          echo "Username: ${{ secrets.SSH_USERNAME }}"
          echo "Key set? -> ${{ secrets.SSH_KEY != '' }}"
          echo "Port: 22"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd "${{ secrets.APP_PATH }}"
            ./build.sh
