name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd "${{ secrets.APP_PATH }}"

             APP_PATH="${{ secrets.APP_PATH }}"
            REPO_URL="https://${{ secrets.GIT_TOKEN }}@github.com/KYKY62/backend_stunting_lkt.git"
            echo "Running build script..."

            if [ ! -d "$APP_PATH/.git" ]; then
              echo "[1] Project not found. Cloning fresh repo..."
              rm -rf "$APP_PATH"
              git clone "$REPO_URL" "$APP_PATH"
            else
              echo "[1] Project exists. Updating repo..."
              cd "$APP_PATH"
              git config --global --add safe.directory "$APP_PATH"
            fi
            ./build.sh
