name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd "${{ secrets.APP_PATH }}"
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod 755 "${{ secrets.APP_PATH }}"build.sh
            ./build.sh
